name: CICD

on:
  create:
    tags:
      - v* 

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Load MongoDB binary cache
      id: cache-mongodb-binaries
      uses: action/cache@v3
      with:
        path: ./.cache/mongodb-binaries
        key: ${{ matrix.node-version }}

    - name: Run Unit Tests
      run: make test
        
    - name: Build and push to Docker Registry
      uses: docker/build-push-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/ms-template
        target: release
        tags: latest
        add_git_labels: true
        tag_with_ref: true