name: CICD

on:
  create:
    tags:
      - v* 

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/ms-template

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Start service
    #   run: make start

    # - name: Load MongoDB cache binaries
    #   id: cache-mongodb-binaries
    #   uses: actions/cache@v3
    #   with:
    #     path: ./node_modules/.cache/mongodb-binaries
    #     key: ${{ runner.os }}-mongodb-binaries

    # - name: Run Unit Tests
    #   run: make test-exec
        
    - name: Build and push to Docker Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        target: release
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}